"""
Exception raised when the app fails to process the request and due to an error it couldn't handle correctly
"""
__author__ = "Rinzler<github.com/feliphebueno>"


class InternalException(BaseException):
    """
    InternalException
    """
    pass
